/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { Shop } from "./Shop";
export type { ShopAggregator } from "./ShopAggregator";
