/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { ERC2771Recipient__factory } from "./ERC2771Recipient__factory";
