endpoint = "https://gnfd-testnet-sp-1.bnbchain.org"
rpcAddr = "gnfd-testnet-fullnode-cosmos-us.bnbchain.org:9090"
chainId = "greenfield_5600-1"

## Please replace the ${PrivateKey} with your own Account A's private key
privateKey = "eec6a0c8d5c6a63afaeee319e6126a74d4acb2c2cc4346b1e2af3b6575b615bb"
publicKey = "0x35979BDd030CF42508151FFEDd961263FC50133A"
PasswordFile = "password.txt"
passwordFile = "password.txt"
